// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// solvePath
Rcpp::NumericVector solvePath(const Rcpp::NumericVector& x, int nKnots, int nPaths);
RcppExport SEXP _mplib_solvePath(SEXP xSEXP, SEXP nKnotsSEXP, SEXP nPathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nKnots(nKnotsSEXP);
    Rcpp::traits::input_parameter< int >::type nPaths(nPathsSEXP);
    rcpp_result_gen = Rcpp::wrap(solvePath(x, nKnots, nPaths));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mplib_solvePath", (DL_FUNC) &_mplib_solvePath, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mplib(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
